import os

SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
SECRET_KEY = os.environ.get('SECRET_KEY')
STORMPATH_API_KEY_ID = os.environ.get('STORMPATH_API_KEY_ID')
STORMPATH_API_KEY_SECRET = os.environ.get('STORMPATH_API_KEY_SECRET')
STORMPATH_APPLICATION = os.environ.get('STORMPATH_APPLICATION')
