"""empty message

Revision ID: 04e0bd0e09c7
Revises: a15754b43b59
Create Date: 2016-05-10 21:25:03.860907

"""

# revision identifiers, used by Alembic.
revision = '04e0bd0e09c7'
down_revision = 'a15754b43b59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'self_parking_cost')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('self_parking_cost', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    ### end Alembic commands ###
