"""empty message

Revision ID: 1bbd742b27fc
Revises: 5ba1ee1f4185
Create Date: 2016-05-10 21:43:21.257190

"""

# revision identifiers, used by Alembic.
revision = '1bbd742b27fc'
down_revision = '5ba1ee1f4185'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('hotels', sa.Column('govt_rate_offered', sa.Boolean(), nullable=True))
    op.add_column('hotels', sa.Column('reservation_url', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'reservation_url')
    op.drop_column('hotels', 'govt_rate_offered')
    op.drop_column('hotels', 'description')
    ### end Alembic commands ###
