"""empty message

Revision ID: 2438195f2de1
Revises: cf75c30a03ca
Create Date: 2016-05-10 21:53:10.287307

"""

# revision identifiers, used by Alembic.
revision = '2438195f2de1'
down_revision = 'cf75c30a03ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('hotels', sa.Column('phone', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'phone')
    op.drop_column('hotels', 'address')
    ### end Alembic commands ###
