"""empty message

Revision ID: 2492e8cc8190
Revises: 8cfdcf6ffe77
Create Date: 2016-05-10 21:19:09.163798

"""

# revision identifiers, used by Alembic.
revision = '2492e8cc8190'
down_revision = '8cfdcf6ffe77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('free_wifi', sa.Boolean(), nullable=True))
    op.add_column('hotels', sa.Column('wifi_cost', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'wifi_cost')
    op.drop_column('hotels', 'free_wifi')
    ### end Alembic commands ###
