"""empty message

Revision ID: 4c374461c793
Revises: 9dd3f7bcf9cb
Create Date: 2016-05-06 14:44:01.463818

"""

# revision identifiers, used by Alembic.
revision = '4c374461c793'
down_revision = '9dd3f7bcf9cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('self_parking', sa.Boolean(), nullable=True))
    op.add_column('hotels', sa.Column('self_parking_cost', sa.String(length=200), nullable=True))
    op.add_column('hotels', sa.Column('valet_parking', sa.Boolean(), nullable=True))
    op.add_column('hotels', sa.Column('valet_parking_cost', sa.String(length=200), nullable=True))
    op.drop_column('hotels', 'parking_cost')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('parking_cost', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('hotels', 'valet_parking_cost')
    op.drop_column('hotels', 'valet_parking')
    op.drop_column('hotels', 'self_parking_cost')
    op.drop_column('hotels', 'self_parking')
    ### end Alembic commands ###
