"""empty message

Revision ID: 526673f9f81f
Revises: None
Create Date: 2016-05-04 20:51:56.097356

"""

# revision identifiers, used by Alembic.
revision = '526673f9f81f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('city_url_slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('city_url_slug')
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.Column('free_parking', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.String(length=200), nullable=True),
    sa.Column('resort_fee', sa.String(length=20), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotels')
    op.drop_table('locations')
    ### end Alembic commands ###
