"""empty message

Revision ID: 5ba1ee1f4185
Revises: 650f44e099be
Create Date: 2016-05-10 21:28:05.908788

"""

# revision identifiers, used by Alembic.
revision = '5ba1ee1f4185'
down_revision = '650f44e099be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('resort_fee_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('hotels', sa.Column('valet_parking_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('hotels', sa.Column('wifi_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'wifi_cost')
    op.drop_column('hotels', 'valet_parking_cost')
    op.drop_column('hotels', 'resort_fee_cost')
    ### end Alembic commands ###
