"""empty message

Revision ID: 650f44e099be
Revises: 6914f620c8d1
Create Date: 2016-05-10 21:27:51.185620

"""

# revision identifiers, used by Alembic.
revision = '650f44e099be'
down_revision = '6914f620c8d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'resort_fee_cost')
    op.drop_column('hotels', 'valet_parking_cost')
    op.drop_column('hotels', 'wifi_cost')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('wifi_cost', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('valet_parking_cost', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('resort_fee_cost', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    ### end Alembic commands ###
