"""empty message

Revision ID: 6dce361d2767
Revises: 2438195f2de1
Create Date: 2016-05-13 01:36:46.665170

"""

# revision identifiers, used by Alembic.
revision = '6dce361d2767'
down_revision = '2438195f2de1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    ### end Alembic commands ###
