"""empty message

Revision ID: 9dd3f7bcf9cb
Revises: 526673f9f81f
Create Date: 2016-05-04 21:01:51.504122

"""

# revision identifiers, used by Alembic.
revision = '9dd3f7bcf9cb'
down_revision = '526673f9f81f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('parking_cost', sa.String(length=200), nullable=True))
    op.add_column('hotels', sa.Column('resort_fee_cost', sa.String(length=20), nullable=True))
    op.drop_column('hotels', 'parking')
    op.drop_column('hotels', 'resort_fee')
    op.add_column('hotels', sa.Column('resort_fee', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('parking', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('hotels', 'resort_fee_cost')
    op.drop_column('hotels', 'parking_cost')
    op.drop_column('hotels', 'resort_fee')
    ### end Alembic commands ###
