"""empty message

Revision ID: a15754b43b59
Revises: 67815054300e
Create Date: 2016-05-10 21:21:29.408588

"""

# revision identifiers, used by Alembic.
revision = 'a15754b43b59'
down_revision = '67815054300e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('self_parking_cost', sa.Numeric(precision=3, scale=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'self_parking_cost')
    ### end Alembic commands ###
