"""empty message

Revision ID: b800025b96e3
Revises: bc4348fda87a
Create Date: 2016-05-22 19:30:28.522894

"""

# revision identifiers, used by Alembic.
revision = 'b800025b96e3'
down_revision = 'bc4348fda87a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('cover_image', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'cover_image')
    ### end Alembic commands ###
