"""empty message

Revision ID: bc4348fda87a
Revises: None
Create Date: 2016-05-14 08:10:03.278213

"""

# revision identifiers, used by Alembic.
revision = 'bc4348fda87a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('city_url_slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('city_url_slug')
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('govt_rate_offered', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.Column('reservation_url', sa.String(length=80), nullable=True),
    sa.Column('free_parking', sa.Boolean(), nullable=True),
    sa.Column('self_parking', sa.Boolean(), nullable=True),
    sa.Column('self_parking_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valet_parking', sa.Boolean(), nullable=True),
    sa.Column('valet_parking_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('resort_fee', sa.Boolean(), nullable=True),
    sa.Column('resort_fee_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('free_wifi', sa.Boolean(), nullable=True),
    sa.Column('wifi_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('trip_advisor_rank', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('hotels')
    op.drop_table('locations')
    ### end Alembic commands ###
