"""empty message

Revision ID: cf75c30a03ca
Revises: 1bbd742b27fc
Create Date: 2016-05-10 21:49:43.005847

"""

# revision identifiers, used by Alembic.
revision = 'cf75c30a03ca'
down_revision = '1bbd742b27fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('trip_advisor_rank', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'trip_advisor_rank')
    ### end Alembic commands ###
