"""empty message

Revision ID: d8ce0ca19f92
Revises: 4c374461c793
Create Date: 2016-05-06 14:53:10.896595

"""

# revision identifiers, used by Alembic.
revision = 'd8ce0ca19f92'
down_revision = '4c374461c793'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('star_rating', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'star_rating')
    ### end Alembic commands ###
