"""empty message

Revision ID: eb2d1b9a6244
Revises: 6dce361d2767
Create Date: 2016-05-13 14:18:07.752545

"""

# revision identifiers, used by Alembic.
revision = 'eb2d1b9a6244'
down_revision = '6dce361d2767'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('key', sa.String(length=200)))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'key')
    ### end Alembic commands ###
